//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCIData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCIData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject1.Resources.TestCIData", typeof(TestCIData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfDataModel&gt;
        ///&lt;DataModel&gt;
        ///    &lt;ID&gt;123&lt;/ID&gt;
        ///    &lt;Name&gt;test&lt;/Name&gt;
        ///    &lt;Designation&gt;engineer&lt;/Designation&gt;
        ///    &lt;Country&gt;India&lt;/Country&gt;
        ///  &lt;/DataModel&gt;
        ///  &lt;DataModel&gt;
        ///    &lt;ID&gt;124&lt;/ID&gt;
        ///    &lt;Name&gt;Gisha&lt;/Name&gt;
        ///    &lt;Designation&gt;Software Engineer&lt;/Designation&gt;
        ///    &lt;Country&gt;India&lt;/Country&gt;
        ///  &lt;/DataModel&gt;
        ///&lt;DataModel&gt;
        ///    &lt;ID&gt;124&lt;/ID&gt;
        ///    &lt;Name&gt;Renish&lt;/Name&gt;
        ///    &lt;Designation&gt;Software Engineer&lt;/Designation&gt;
        ///    &lt;Country&gt;India&lt;/Country&gt;
        ///  &lt;/DataModel&gt;
        ///  &lt;DataModel&gt;
        ///    &lt;ID&gt;1235&lt;/ID&gt;
        ///    &lt;Name&gt;Sm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PeopleData {
            get {
                return ResourceManager.GetString("PeopleData", resourceCulture);
            }
        }
    }
}
